os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash
  CYGWIN: NONTSEC

init:
  - 'C:\cygwin\setup-x86.exe -q -P unzip -P chmod'
  - '%CYG_BASH% -lc "mkdir $HOMEPATH/.dnx; chmod 755 $HOMEPATH/.dnx; mkdir $HOMEPATH/.dnx/alias; echo /etc/fstab; echo "none /cygdrive cygdrive binary,noacl,posix=0,user 0 0\n" > /etc/fstab; mkpasswd -l > /etc/passwd; mkgroup -l > /etc/group"'
install:

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm upgrade; dnvm install -r coreclr -arch x64 latest -OS win -u -p; dnvm list; cd $DNX_USER_HOME; ls -Al; cd runtimes; ls -Al; cd dnx-coreclr-win-x64.1.0.0-beta8-15654; ls -A; dnu.cmd"'
 