os: Windows Server 2012 R2

test: off
deploy: off

environment:
  CYG_BASH: C:\cygwin\bin\bash
  CYGWIN: NONTSEC

init:
  - '%CYG_BASH% -lc "cd /etc; echo "none /cygdrive cygdrive binary,noacl,posix=0,user 0 0" > fstab; mkpasswd -l -d > /etc/passwd; mkgroup -l -d > /etc/group"'
install:

  - 'C:\cygwin\setup-x86.exe -q -P unzip'

build_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; source dnvm.sh; dnvm upgrade; dnvm install -r coreclr -arch x64 latest -OS win -u -p; dnvm list; dnu.cmd"'
 